services:
  - type: web
    name: loan-trackr
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: noreply@loantrackr.app
